server:
  port: ${PORT:8084}

spring:
  application:
    name: notification-service

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:theonlymailsender@gmail.com}
    password: ${MAIL_PASSWORD:izzx fbud zdvk uuwi}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: ${MAIL_FROM:theonlymailsender@gmail.com}

rabbit:
  exchange: healthcare.exchange
  queue: appointment.queue
  routing-key: healthcare.routingkey

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.healthcare.notification: DEBUG