server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL:lb://auth-service}
          predicates:
            - Path=/api/auth/**

        - id: patient-service-route
          uri: ${PATIENT_SERVICE_URL:lb://patient-service}
          predicates:
            - Path=/api/patients/**

        - id: doctor-service-route
          uri: ${DOCTOR_SERVICE_URL:lb://doctor-service}
          predicates:
            - Path=/api/doctors/**

        - id: appointment-service-route
          uri: ${APPOINTMENT_SERVICE_URL:lb://appointment-service}
          predicates:
            - Path=/api/appointments/**

        - id: inventory-service-route
          uri: ${INVENTORY_SERVICE_URL:lb://inventory-service}
          predicates:
            - Path=/api/medicines/**

        - id: pharmacist-service-route
          uri: ${PHARMACIST_SERVICE_URL:lb://pharmacist-service}
          predicates:
            - Path=/api/pharmacists/**

        - id: receptionist-service-route
          uri: ${RECEPTIONIST_SERVICE_URL:lb://receptionist-service}
          predicates:
            - Path=/api/receptionists/**

        - id: prescription-service-route
          uri: ${PRESCRIPTION_SERVICE_URL:lb://prescription-service}
          predicates:
            - Path=/api/prescriptions/**

jwt:
  secret: ${JWT_SECRET}
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.healthcare.apigateway: DEBUG
    org.springframework.cloud.gateway: TRACE
