server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: patient-service-route
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**

        - id: doctor-service-route
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**

        - id: appointment-service-route
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**

        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/medicines/**

        - id: pharmacist-service-route
          uri: lb://pharmacist-service
          predicates:
            - Path=/api/pharmacists/**

        - id: receptionist-service-route
          uri: lb://receptionist-service
          predicates:
            - Path=/api/receptionists/**

        - id: prescription-service-route
          uri: lb://prescription-service
          predicates:
            - Path=/api/prescriptions/**

jwt:
  secret: ${JWT_SECRET:V6fTF1MzMy9RZTvoV7x7VoVGLXmgtVXHUdMOAHyn6Wg=}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@localhost:8761/eureka/}
      registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.healthcare.apigateway: DEBUG
    org.springframework.cloud.gateway: TRACE
